spring:

  docker:
    compose:
      lifecycle-management: start_only

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    locations: classpath:db/migration

stripe:
  apikey: ${STRIPE_SECRET_KEY}


logging:
  level:
    org:
      springframework:
        security: trace