spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}-prod
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}